// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7eEIbpNWWcdmVaTwUV6bcTZlijPo29C4',
    appId: '1:962155010783:web:3ccedca5a5e872f210676a',
    messagingSenderId: '962155010783',
    projectId: 'champe-2a77b',
    authDomain: 'champe-2a77b.firebaseapp.com',
    storageBucket: 'champe-2a77b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZVCOxrtriyWLHOv4NbMeGyML3wO57hY',
    appId: '1:962155010783:android:50146541116d24d510676a',
    messagingSenderId: '962155010783',
    projectId: 'champe-2a77b',
    storageBucket: 'champe-2a77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvQt7fu8ioF6GtFy95TN2gdGgxIEmPgU',
    appId: '1:962155010783:ios:d808ff759705517510676a',
    messagingSenderId: '962155010783',
    projectId: 'champe-2a77b',
    storageBucket: 'champe-2a77b.appspot.com',
    iosBundleId: 'com.gabina.champe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcvQt7fu8ioF6GtFy95TN2gdGgxIEmPgU',
    appId: '1:962155010783:ios:d808ff759705517510676a',
    messagingSenderId: '962155010783',
    projectId: 'champe-2a77b',
    storageBucket: 'champe-2a77b.appspot.com',
    iosBundleId: 'com.gabina.champe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7eEIbpNWWcdmVaTwUV6bcTZlijPo29C4',
    appId: '1:962155010783:web:7ea23139e45c9d7f10676a',
    messagingSenderId: '962155010783',
    projectId: 'champe-2a77b',
    authDomain: 'champe-2a77b.firebaseapp.com',
    storageBucket: 'champe-2a77b.appspot.com',
  );
}
